In [21]:
text=['This is a line',
     'This is another line',
     'Completely different line']

In [22]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [23]:
cv=CountVectorizer()

In [24]:
sparse_matrix=cv.fit_transform(text)

In [25]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [26]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [15]:
cv=CountVectorizer(stop_words='english')

In [16]:
sparse_matrix=cv.fit_transform(text)

In [17]:
sparse_matrix.todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]], dtype=int64)

In [18]:
cv.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

In [27]:
tfidf=TfidfTransformer()

In [30]:
#After running starting cell of sparse matrix
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [32]:
results=tfidf.fit_transform(sparse_matrix) #BOW---->TF-IDF

In [33]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [36]:
tv=TfidfVectorizer()

In [37]:
tv_results=tv.fit_transform(text)

In [38]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])